name: Generate Wallpapers README

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 0 * * 0' # optional: weekly

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate README.md
        run: |
          echo "# Wallpaper Collection" > README.md
          echo "" >> README.md
          echo "Install:" >> README.md
          echo "```sh" >> README.md
          echo "git clone --depth 1 https://github.com/phucisstupid/wallpapers" >> README.md
          echo "```" >> README.md
          echo "" >> README.md
          echo "<table>" >> README.md
          count=0
          echo "<tr>" >> README.md
          for img in *.png *.jpg *.jpeg *.webp; do
            if [ ! -f "$img" ]; then continue; fi
            echo "<td><a href=\"$img\"><img src=\"$img\" width=\"200\" /></a></td>" >> README.md
            count=$((count+1))
            if [ $count -eq 4 ]; then
              echo "</tr><tr>" >> README.md
              count=0
            fi
          done
          echo "</tr>" >> README.md
          echo "</table>" >> README.md

      - name: Commit and push README
        run: |
          git add README.md
          git commit -m "Update README with wallpapers" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
