name: Generate Wallpapers README

on:
  workflow_dispatch: # manual trigger
  workflow_run:
    workflows: ["Stole Wallpapers"]
    types:
      - completed

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate README
        run: |
          TOTAL=$(find . -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) | wc -l)

          cat > README.md <<EOF
          # 🖼 Wallpapers
          A collection of **high-quality 4K aesthetic wallpapers**. Perfect for desktops, backgrounds, and inspiration!
          
          ### 🚀 This repository updates **wallpapers every week**.
          #### Why?
          - Perfect for people who like to **change their wallpaper daily** → 16 wallpapers for a week = 2/3 per day
          - Keeps the repo size small.

          ## Get all wallpapers
          \`\`\`sh
          git clone --depth 1 https://github.com/phucisstupid/wallpapers
          \`\`\`

          ## Update wallpapers
          Run this to always get the latest wallpapers:

          \`\`\`sh
          git fetch origin && git reset --hard origin/main
          \`\`\`

          ## Gallery
          ![Total Wallpapers](https://img.shields.io/badge/Total-$TOTAL-blue)
          💡 Tip: Click on any image to view full-size. Enjoy your wallpapers!

          <table>
          <tr>
          EOF

          count=0
          find . -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) | sort | while read img; do
            echo "<td><a href=\"$img\"><img src=\"$img\" width=\"200\" /></a></td>" >> README.md
            count=$((count+1))
            if [ $count -eq 4 ]; then
              echo "</tr><tr>" >> README.md
              count=0
            fi
          done

          echo "</tr></table>" >> README.md

      - name: Commit and push
        run: |
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
