name: Generate Wallpapers README

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: '0 0 * * 0' # optional: weekly

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate README
        run: |
          echo "# 🖼 Wallpapers" > README.md
          echo "" >> README.md
          echo "A collection of **high-quality 4K aesthetic wallpapers**. Perfect for desktops, backgrounds, and inspiration!" >> README.md
          echo "" >> README.md

          # Count all image files recursively
          TOTAL=$(find . -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) | wc -l)
          echo "![Total Wallpapers](https://img.shields.io/badge/Total-$TOTAL-blue)" >> README.md
          echo "" >> README.md

          echo "## Get all wallpapers" >> README.md
          echo '```sh' >> README.md
          echo 'git clone --depth 1 https://github.com/phucisstupid/wallpapers' >> README.md
          echo '```' >> README.md
          echo "" >> README.md

          echo "## Gallery" >> README.md
          echo "💡 Tip: Click on any image to view full-size. Enjoy your wallpapers!" >> README.md
          echo "<table>" >> README.md
          count=0
          echo "<tr>" >> README.md

          # Loop over all image files recursively
          find . -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) | sort | while read img; do
            echo "<td><a href=\"$img\"><img src=\"$img\" width=\"200\" /></a></td>" >> README.md
            count=$((count+1))
            if [ $count -eq 4 ]; then
              echo "</tr><tr>" >> README.md
              count=0
            fi
          done

          echo "</tr>" >> README.md
          echo "</table>" >> README.md

      - name: Commit and push
        run: |
          git add README.md
          git commit -m "Update README" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
