name: Stole Wallpapers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  fetch-wallpapers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Delete old wallpapers
        run: |
          find $GITHUB_WORKSPACE -maxdepth 1 -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) -delete

      - name: Download wallpapers repo
        run: |
          git clone --depth=1 https://github.com/makccr/wallpapers temp-wallpapers
          cd temp-wallpapers/wallpapers
          find . -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.webp' \) -exec cp {} $GITHUB_WORKSPACE/ \;
          cd $GITHUB_WORKSPACE
          rm -rf temp-wallpapers

      - name: Commit and push
        run: |
          git add .
          git commit -m "Update wallpapers" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
